### PR TITLE
Bugfixes and slight color improvements

### PR DESCRIPTION
**Pull request by ankitchhatbar**
Fixed a few bugs, changed the theme colors and made some design tweaks. This could be another version of the same theme

### CODE REVIEW

**Comment by jeremiecook** [comment]
Hi ! And thanks for your work !
You seems to have worked on protonmail.css file only. This file is generated from scss files (in src folder). I can't review / merge your changes, or all edits will be lost next update :/

Could you edit scss files or explain the bugs you fixed ?

Thanks !

**Comment by ankitchhatbar** [comment]
Hello,
Here are the bugs that I have fixed. 
See the below Image. The content overlaps the more menu. Fixed it.
image

The storage used indicator not showing and links disappearing on hover. was fixed.
image

I have also made many colors and layout changes and the theme also feels different. So can be put as a different version.

Please check the changes by implementing the CSS file. If you like them, I can edit the CSS file and send you.

Thanks.

**Comment by jeremiecook** [comment]
Thanks for the screenshot! The thing is : all changes must be edited in scss files, not css. CSS is compressed and only meant to be use as a theme. If you can tell me which parts of the code you changed exactly, I can add it :)

**Comment by ankitchhatbar** [comment]
I have sent you another pull request with the SCSS edited. You can delete this one.

**Pull request closed without merging**
